services:
  - type: web
    name: githelp
    runtime: node
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: githelp-db
          property: connectionString
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_EMBEDDING_MODEL
        value: text-embedding-004
      - key: GEMINI_CHAT_MODEL
        value: gemini-1.5-pro
      - key: GEMINI_LOCATION
        value: us-central1

databases:
  - name: githelp-db
    databaseName: githelp
    user: githelp
    plan: free